practice_exam_defaults:
  practice_deadline: "{{截止时间}}"
  practice_submission_path: "超星学习通。逾期未提交且未提前申请缓考将视为学生旷考/缺考，请知悉。"
  practice_others: |
    （1）{{截止时间}}，逾期未提交未提前缓考申请的，将视为自主放弃本次考核资格，并按旷考、缺考记录。
    （2）旷考、缺考或违纪作弊、抄袭（作品中所使用的主素材必须是作者原创，个别素材使用公共素材的，必须注明出处，否则视为作弊、抄袭），该门课程按照总成绩不合格处理，不允许参加重考。
    （3）重考、缓考使用的是期末正考未启用过的试题，重缓考学生不得提交过往提交过的作品（含个人或他人/队员作品），否则将作抄袭、作弊处理，成绩为0。
